site_name: Smelly Cat's Wiki
site_author: Eric
site_url: http://wiki.choumaomi.com
site_description: '个人编程经验分享，wiki码农库'
docs_dir: 'docs'
# 左侧导航
nav:
- 主页: index.md
- python:
    - Flask的学习:
        - flask起步: Flask_study/1Flask起步.md
        - flask与http: Flask_study/2Flask与Http.md
        - 模板: Flask_study/3模板.md
        - 表单: Flask_study/4表单.md
        - 数据库: Flask_study/5数据库.md
        - 插件 :
            - flask_moment: Flask_study/flask_moment.md
            - getenv: Flask_study/getenv获取环境变量.md
    - ORM:
        - MongoEngine: ORM/MongoEngine官方文档.md
        - SqlAlchemy: ORM/SqlAlchemy的官方文档.md

    - python基础:
        - 面向对象: python_study/python面向对象的相关概念.md
        - 同步和异步 : python_study/同步和异步.md
        - 排序 : python_study/排序.md
        - 数据结构: python_study/数据结构.md
        - 继承和多态: python_study/继承和多态.md
        - 定制类: python_study/定制类.md
        - 获得对象信息: python_study/获得对象信息.md
        - 虚拟环境配置: python_study/虚拟环境配置.md
        - 进程&线程&协程: python_study/进程&线程&协程.md
        - 通过类创建子进程: python_study/通过类创建子进程.md
        - 面向对象变成: python_study/面向对象编程.md
        - IO编程: python_study/IO编程.md
        - staticmethod和classmethod: python_study/@staticmethod和@classmethod.md
        - dict和set: python_study/使用dict和set.md
        - gunicorn部署flask: python_study/使用gunicorn部署flask项目.md
- 架构及开发工具:
    - DevOps介绍: 架构及开发工具/Devops.md
    - RabbitMq使用: 架构及开发工具/rabbitmq.md
- 数据库:
    - pgsql的安装: 数据库/centos安装pgsql.md
- 面试题:
    - 面试题: 面试题/面试题.md
- 工具包:
    - logging模块: 工具包/logging模块.md
    - 保留小数: 工具包/保留小数.md
    - 收藏网站: 工具包/收藏网站.md
- 个人学习:
    - 源码学习:
        - 第一天: 源码学习/第一天源码学习.md
- 项目数据结构:
  - 教学系统数据结构: EduSystemDataStructure.md
  - 博客网站数据结构: BlogDataStructure.md

- mkdocs使用方法:
    - '流程图': flow_method.md
- 读书:
    - 定位逻辑: 读书/定位逻辑.md
    - 找对英语学习方法的第一本书: 读书/找对英语学习方法的第一本书.md
    - 能力陷阱: 读书/能力陷阱.md
    - 责任病毒: 读书/责任病毒.md
    - 销售就是要玩转情商: 读书/销售就是玩转情商.md

# 本地调试端口
dev_addr: 127.0.0.1:9008

theme:
  name: material
  custom_dir: assets
  language: 'zh'
  favicon: 'img/favicon.png'
  logo: 'img/favicon.png'
  palette:
    primary: 'Light Blue'
    accent: 'Light Blue'
  feature:
    tabs: false
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

# 自定义css
extra_css:
- 'css/custom.css'
- 'css/simpleLightbox.min.css'

# 自定义js
extra_javascript:
- 'js/jquery-3.1.1.min.js'
- 'js/simpleLightbox.min.js'
- 'https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js'
- 'https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js'
- 'https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js'
- 'https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js'
- 'js/umlconvert.js'
- 'js/custom.js'


# 一些扩展
markdown_extensions:
  - pymdownx.superfences
  - smarty
  - markdown.extensions.attr_list
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist
  - pymdownx.tilde
